/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Class.ClientePF;
import Class.ClientePJ;
import Controller.NegocioClientePF;
import Controller.NegocioClientePJ;
import Data.DadosClientePF;
import Data.DadosClientePJ;
import java.awt.event.MouseEvent;
import java.sql.Date;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Pichau
 */
public class ViewCadastroClientes extends javax.swing.JFrame {

    /**
     * Creates new form TelaOperacoesClientes
     */
    
    
    public ViewCadastroClientes() {
        initComponents();
        setLocationRelativeTo(null);
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        jTextFieldData.setText(formato.format(new Date(System.currentTimeMillis())));
        jTextFieldNomeEmpresa.setEnabled(false);
    }
    public void TextLabel(String jLabel, String jLabel2) {
        jLabelNome.setText(jLabel);
        jLabelCPF.setText(jLabel2);
    }
    private void ListarCnpjTable() {
        try {
            try {
                ClientePJ clientepj = new ClientePJ();
                DadosClientePJ dadosClientePJ = new DadosClientePJ();
                this.respostaClientePJ = dadosClientePJ.listarClientePJ(clientepj);
                DefaultTableModel modelo = new DefaultTableModel();
                modelo.setColumnIdentifiers(new Object[]{"Razão Social", "CNPJ", "Empresa"});
                for (ClientePJ c : this.respostaClientePJ) {
                    modelo.addRow(new Object[]{c.getRazaoSocial(), c.getCnpj(), c.getNomeEmpresa()});
                }
                jTable1.setModel(modelo);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    private void ListarCpfTable() {
        try {
            try {
                ClientePF clientepf = new ClientePF();
                DadosClientePF dadosClientePF = new DadosClientePF();
                this.respostaClientePF = dadosClientePF.listarClientePF(clientepf);
                DefaultTableModel modelo = new DefaultTableModel();
                modelo.setColumnIdentifiers(new Object[]{"Nome", "CPF", "Telefone"});
                for (ClientePF c : this.respostaClientePF) {
                    modelo.addRow(new Object[]{c.getNome(), c.getCpf(), c.getTelefone_PF()});
                }
                jTable1.setModel(modelo);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    private void ApagandoTextFileds()
    {
        jTextFieldNome.setText("");
        jTextFieldCPF.setText("");
        jTextFieldEndereco.setText("");
        jTextFieldBairro.setText("");
        jTextFieldTelefone.setText("");
        jTextFieldNomeEmpresa.setText("");
        jTextFieldCidade.setText("");
        jTextFieldEstado.setText("");
    }   
    ArrayList<ClientePJ> respostaClientePJ;
    ArrayList<ClientePF> respostaClientePF;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jProgressBar1 = new javax.swing.JProgressBar();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jTextFieldNomeEmpresa = new javax.swing.JTextField();
        jTextFieldNome = new javax.swing.JTextField();
        jTextFieldCPF = new javax.swing.JTextField();
        jLabelCPF = new javax.swing.JLabel();
        jLabelNomeEmpresa = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        jTextFieldEstado = new javax.swing.JTextField();
        jLabelEstado = new javax.swing.JLabel();
        jLabelCidade = new javax.swing.JLabel();
        jTextFieldCidade = new javax.swing.JTextField();
        jTextFieldBairro = new javax.swing.JTextField();
        jLabelBairro = new javax.swing.JLabel();
        jLabelEndereco = new javax.swing.JLabel();
        jTextFieldEndereco = new javax.swing.JTextField();
        jLabelData = new javax.swing.JLabel();
        jTextFieldData = new javax.swing.JTextField();
        try 
        {
            javax.swing.text.MaskFormatter dataFormat = new MaskFormatter("##/##/####");             
            jTextFieldData = new javax.swing.JFormattedTextField(dataFormat);         
        } 
        catch (Exception e) {

            JOptionPane.showMessageDialog(null, e.getMessage());         
        }
        jLabelTelefone = new javax.swing.JLabel();
        jTextFieldTelefone = new javax.swing.JTextField();
        try 
        {
            javax.swing.text.MaskFormatter cnpj = new MaskFormatter("(##)#####-####");             
            jTextFieldTelefone = new javax.swing.JFormattedTextField(cnpj);         
        } 
        catch (Exception e) {

            JOptionPane.showMessageDialog(null, e.getMessage());         
        }
        jRadioButtonClientePJ = new javax.swing.JRadioButton();
        jRadioButtonClientePF = new javax.swing.JRadioButton();
        jButtonCadastrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jRadioButtonListarFisicas = new javax.swing.JRadioButton();
        jRadioButtonListarJuridicas = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelAviso = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jButtonEditar = new javax.swing.JButton();
        jLabelAviso2 = new javax.swing.JLabel();
        jLabelEditarNome = new javax.swing.JLabel();
        jLabelEditarCPF = new javax.swing.JLabel();
        jLabelEditarEmpresa = new javax.swing.JLabel();
        jLabelEdtiarEstado = new javax.swing.JLabel();
        jLabelEditarCidade = new javax.swing.JLabel();
        jLabelEditarBairro = new javax.swing.JLabel();
        jLabelEdtiarEndereco = new javax.swing.JLabel();
        jLabelEditarTelefone = new javax.swing.JLabel();
        jTextFieldEditarNome = new javax.swing.JTextField();
        jTextFieldEditarCPF = new javax.swing.JTextField();
        jTextFieldEditarEmpresa = new javax.swing.JTextField();
        jTextFieldEditarEstado = new javax.swing.JTextField();
        jTextFieldEditarCidade = new javax.swing.JTextField();
        jTextFieldEditarBairro = new javax.swing.JTextField();
        jTextFieldEditarEndereco = new javax.swing.JTextField();
        jTextFieldEditarTelefone = new javax.swing.JTextField();
        try 
        {
            javax.swing.text.MaskFormatter cnpj = new MaskFormatter("(##)#####-####");             
            jTextFieldEditarTelefone = new javax.swing.JFormattedTextField(cnpj);         
        } 
        catch (Exception e) {

            JOptionPane.showMessageDialog(null, e.getMessage());         
        }
        jButtonConcluirEdicao = new javax.swing.JButton();
        jTextFieldPesquisarCPF = new javax.swing.JTextField();
        jButtonPesquisar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTextFieldNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNomeKeyTyped(evt);
            }
        });

        jTextFieldCPF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCPFKeyTyped(evt);
            }
        });

        jLabelCPF.setText("CPF");

        jLabelNomeEmpresa.setText("Empresa");

        jLabelNome.setBackground(new java.awt.Color(0, 102, 204));
        jLabelNome.setText("Nome");

        jTextFieldEstado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldEstadoKeyTyped(evt);
            }
        });

        jLabelEstado.setText("Estado");

        jLabelCidade.setText("Cidade");

        jTextFieldCidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCidadeKeyTyped(evt);
            }
        });

        jLabelBairro.setText("Bairro");

        jLabelEndereco.setText("Endereço");

        jLabelData.setText("Data");

        jTextFieldData.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldDataKeyTyped(evt);
            }
        });

        jLabelTelefone.setText("Telefone");

        jTextFieldTelefone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldTelefoneKeyTyped(evt);
            }
        });

        buttonGroup1.add(jRadioButtonClientePJ);
        jRadioButtonClientePJ.setText("PJ");
        jRadioButtonClientePJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonClientePJActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonClientePF);
        jRadioButtonClientePF.setText("PF");
        jRadioButtonClientePF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonClientePFActionPerformed(evt);
            }
        });

        jButtonCadastrar.setText("Cadastrar");
        jButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTable1KeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        buttonGroup2.add(jRadioButtonListarFisicas);
        jRadioButtonListarFisicas.setText("PF");
        jRadioButtonListarFisicas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonListarFisicasActionPerformed(evt);
            }
        });

        buttonGroup2.add(jRadioButtonListarJuridicas);
        jRadioButtonListarJuridicas.setText("PJ");
        jRadioButtonListarJuridicas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonListarJuridicasActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabelAviso.setText("Clique duas vezes para remover um cliente");

        jButtonEditar.setText("Editar");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jLabelAviso2.setText("Editar");

        jLabelEditarNome.setText("Nome / Razão");

        jLabelEditarCPF.setText("CPF / CNPJ");

        jLabelEditarEmpresa.setText("Empresa");

        jLabelEdtiarEstado.setText("Estado");

        jLabelEditarCidade.setText("Cidade");

        jLabelEditarBairro.setText("Bairro");

        jLabelEdtiarEndereco.setText("Endereço");

        jLabelEditarTelefone.setText("Telefone");

        jTextFieldEditarCPF.setEditable(false);
        jTextFieldEditarCPF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldEditarCPFKeyTyped(evt);
            }
        });

        jTextFieldEditarEstado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldEditarEstadoKeyTyped(evt);
            }
        });

        jTextFieldEditarCidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldEditarCidadeKeyTyped(evt);
            }
        });

        jTextFieldEditarBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEditarBairroActionPerformed(evt);
            }
        });

        jTextFieldEditarTelefone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldEditarTelefoneKeyTyped(evt);
            }
        });

        jButtonConcluirEdicao.setText("Concluir");
        jButtonConcluirEdicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConcluirEdicaoActionPerformed(evt);
            }
        });

        jTextFieldPesquisarCPF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldPesquisarCPFKeyTyped(evt);
            }
        });

        jButtonPesquisar.setText("Pesquisar CPF");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jRadioButtonListarFisicas)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jRadioButtonListarJuridicas)
                                            .addGap(27, 27, 27)
                                            .addComponent(jTextFieldPesquisarCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jButtonPesquisar)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButtonEditar)))
                                    .addComponent(jLabelAviso)
                                    .addComponent(jLabelNome)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelBairro)
                                            .addComponent(jLabelEndereco))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelCidade)
                                        .addGap(16, 16, 16)
                                        .addComponent(jTextFieldCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelCPF)
                                            .addComponent(jTextFieldCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldNomeEmpresa)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabelNomeEmpresa)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(47, 47, 47)
                                                        .addComponent(jRadioButtonClientePJ)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(jRadioButtonClientePF)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(jButtonCadastrar)))
                                                .addGap(0, 0, Short.MAX_VALUE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelEstado)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabelData)
                                                .addGap(24, 24, 24)
                                                .addComponent(jTextFieldData, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabelTelefone)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(4, 4, 4)))
                                .addGap(14, 14, 14)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButtonConcluirEdicao)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldEditarCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelEditarEmpresa)
                                    .addComponent(jLabelEditarCPF)
                                    .addComponent(jLabelEditarTelefone)
                                    .addComponent(jTextFieldEditarTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldEditarEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelEdtiarEndereco)
                                    .addComponent(jTextFieldEditarBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelEditarBairro)
                                    .addComponent(jTextFieldEditarCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelEditarCidade)
                                    .addComponent(jTextFieldEditarEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelEdtiarEstado)
                                    .addComponent(jTextFieldEditarEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldEditarNome, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabelEditarNome))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelAviso2)
                        .addGap(67, 67, 67))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNomeEmpresa)
                            .addComponent(jLabelCPF))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNomeEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelEstado)
                            .addComponent(jLabelTelefone)
                            .addComponent(jTextFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelCidade)
                            .addComponent(jLabelData, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelBairro))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelEndereco)
                            .addComponent(jTextFieldEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButtonClientePJ)
                            .addComponent(jRadioButtonClientePF)
                            .addComponent(jButtonCadastrar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelAviso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButtonListarJuridicas)
                            .addComponent(jRadioButtonListarFisicas)
                            .addComponent(jButtonEditar)
                            .addComponent(jTextFieldPesquisarCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonPesquisar))
                        .addContainerGap(29, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelAviso2)
                        .addGap(8, 8, 8)
                        .addComponent(jLabelEditarNome)
                        .addGap(11, 11, 11)
                        .addComponent(jTextFieldEditarNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelEditarCPF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldEditarCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelEditarEmpresa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldEditarEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelEdtiarEstado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldEditarEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelEditarCidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldEditarCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelEditarBairro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldEditarBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelEdtiarEndereco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldEditarEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelEditarTelefone)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldEditarTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonConcluirEdicao)
                        .addGap(28, 28, 28))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarActionPerformed

        if (jRadioButtonClientePF.isSelected() == true) {
            try {
                ClientePF clientepf = new ClientePF();
                SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
                Date dataCadastro = new java.sql.Date(formato.parse(jTextFieldData.getText()).getTime());
                clientepf.setNome(jTextFieldNome.getText());
                clientepf.setCpf(jTextFieldCPF.getText());
                clientepf.setEndereco_PF(jTextFieldEndereco.getText());
                clientepf.setBairro_PF(jTextFieldBairro.getText());
                clientepf.setEstado_PF(jTextFieldEstado.getText());
                clientepf.setTelefone_PF(jTextFieldTelefone.getText());
                clientepf.setDataCadastro_PF(dataCadastro);
                clientepf.setCidade_PF(jTextFieldCidade.getText());

                NegocioClientePF negocioClientePF = new NegocioClientePF();
                negocioClientePF.cadastrarClientePF(clientepf);
                JOptionPane.showMessageDialog(this, "Cliente cadastrado", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                ApagandoTextFileds();
                ListarCpfTable();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage(), "Aviso", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            if (jRadioButtonClientePJ.isSelected() == true) {
                try {
                    ClientePJ clientepj = new ClientePJ();
                    SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
                    Date dataCadastro = new java.sql.Date(formato.parse(jTextFieldData.getText()).getTime());
                    clientepj.setRazaoSocial(jTextFieldNome.getText());
                    clientepj.setCnpj(jTextFieldCPF.getText());
                    clientepj.setEndereco_PJ(jTextFieldEndereco.getText());
                    clientepj.setBairro_PJ(jTextFieldBairro.getText());
                    clientepj.setTelefone_PJ(jTextFieldTelefone.getText());
                    clientepj.setDataCadastro_PJ(dataCadastro);
                    clientepj.setNomeEmpresa(jTextFieldNomeEmpresa.getText());
                    clientepj.setCidade_PJ(jTextFieldCidade.getText());
                    clientepj.setEstado_PJ(jTextFieldEstado.getText());

                    NegocioClientePJ negocioClientePJ = new NegocioClientePJ();
                    negocioClientePJ.cadastrarClientePJ(clientepj);
                    JOptionPane.showMessageDialog(this, "Cliente cadastrado", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                    ApagandoTextFileds();
                    ListarCnpjTable();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, e.getMessage(), "Aviso", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Escolha PJ ou PF", "Aviso", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButtonCadastrarActionPerformed

    private void jRadioButtonClientePFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonClientePFActionPerformed
        TextLabel("Nome", "CPF");
        jTextFieldNomeEmpresa.setEnabled(false);
    }//GEN-LAST:event_jRadioButtonClientePFActionPerformed

    private void jRadioButtonClientePJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonClientePJActionPerformed
        TextLabel("Razão Social", "CNPJ");
        jTextFieldNomeEmpresa.setEnabled(true);
    }//GEN-LAST:event_jRadioButtonClientePJActionPerformed

    private void jRadioButtonListarJuridicasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonListarJuridicasActionPerformed
        ListarCnpjTable();
        jTextFieldEditarEmpresa.setEnabled(true);
        jButtonPesquisar.setText("Pesquisar CNPJ");
    }//GEN-LAST:event_jRadioButtonListarJuridicasActionPerformed

    private void jRadioButtonListarFisicasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonListarFisicasActionPerformed
        ListarCpfTable();
        jTextFieldEditarEmpresa.setEnabled(false);
        jButtonPesquisar.setText("Pesquisar CPF");
    }//GEN-LAST:event_jRadioButtonListarFisicasActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        MouseEvent e = evt;
        int index = jTable1.getSelectedRow();
        int click = e.getClickCount();
        if(jRadioButtonListarFisicas.isSelected() == false && jRadioButtonListarJuridicas.isSelected() == false)
        {
            JOptionPane.showMessageDialog(this, "Selecione o tipo de pessoa (PF/PJ)", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
        if (jRadioButtonListarFisicas.isSelected() == true) {
            try {
                if (click == 2) {
                    if (index >= 0) {
                        ClientePF clientepf = this.respostaClientePF.get(index);
                        String mensagem = "Deseja remover este cliente?\nCliente: " + clientepf.getNome() + "\nCPF: " + clientepf.getCpf() + "\nTelefone: " + clientepf.getTelefone_PF();
                        int resultado = JOptionPane.showConfirmDialog(this, mensagem, "Remover cliente", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                        if (resultado == JOptionPane.YES_OPTION) {

                            NegocioClientePF negocioClientePF = new NegocioClientePF();
                            negocioClientePF.excluirClientePF(clientepf);
                            ListarCpfTable();
                            JOptionPane.showMessageDialog(this, "Cliente removido", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                        }
                    }
                }

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Atenção", JOptionPane.WARNING_MESSAGE);
            }
        }
        if (jRadioButtonListarJuridicas.isSelected() == true) {
            try {
                if (click == 2) {
                    if (index >= 0) {
                        ClientePJ clientepj = this.respostaClientePJ.get(index);
                        String mensagem = "Deseja remover este cliente?\nCliente: " + clientepj.getRazaoSocial() + "\nCNPJ: " + clientepj.getCnpj() + "\nEmpresa: " + clientepj.getNomeEmpresa();
                        int resultado = JOptionPane.showConfirmDialog(this, mensagem, "Remover cliente", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                        if (resultado == JOptionPane.YES_OPTION) {

                            DadosClientePJ DadosClientePJ = new DadosClientePJ();
                            DadosClientePJ.excluirClientePJ(clientepj);
                            ListarCnpjTable();
                            JOptionPane.showMessageDialog(this, "Cliente removido", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                        }
                    }
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Atenção", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyTyped
        jTable1.editingCanceled(null);
        jTable1.editingStopped(null);
    }//GEN-LAST:event_jTable1KeyTyped

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed
        jTable1.editingCanceled(null);
        jTable1.editingStopped(null);
    }//GEN-LAST:event_jTable1MousePressed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        int index = jTable1.getSelectedRow();
        if (jRadioButtonListarFisicas.isSelected() == true) {
            try {
                if (index >= 0) {
                    ClientePF clientepf = this.respostaClientePF.get(index);
                    jTextFieldEditarNome.setText(clientepf.getNome());
                    jTextFieldEditarCPF.setText(clientepf.getCpf());
                    jTextFieldEditarEstado.setText(clientepf.getEstado_PF());
                    jTextFieldEditarCidade.setText(clientepf.getCidade_PF());
                    jTextFieldEditarBairro.setText(clientepf.getBairro_PF());
                    jTextFieldEditarEndereco.setText(clientepf.getEndereco_PF());
                    jTextFieldEditarTelefone.setText(clientepf.getTelefone_PF());
                }

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Atenção", JOptionPane.WARNING_MESSAGE);
            }
        }
        if (jRadioButtonListarJuridicas.isSelected() == true) {
            try {
                if (index >= 0) {
                    ClientePJ clientepj = this.respostaClientePJ.get(index);
                    jTextFieldEditarNome.setText(clientepj.getRazaoSocial());
                    jTextFieldEditarCPF.setText(clientepj.getCnpj());
                    jTextFieldEditarEstado.setText(clientepj.getEstado_PJ());
                    jTextFieldEditarCidade.setText(clientepj.getCidade_PJ());
                    jTextFieldEditarBairro.setText(clientepj.getBairro_PJ());
                    jTextFieldEditarEndereco.setText(clientepj.getEndereco_PJ());
                    jTextFieldEditarTelefone.setText(clientepj.getTelefone_PJ());
                    jTextFieldEditarEmpresa.setText(clientepj.getNomeEmpresa());
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Atenção", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonConcluirEdicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConcluirEdicaoActionPerformed
        if (jRadioButtonListarFisicas.isSelected() == true) {
            try {               
                ClientePF clientepf = new ClientePF();
                clientepf.setNome(jTextFieldEditarNome.getText());
                clientepf.setCpf(jTextFieldEditarCPF.getText());
                clientepf.setEndereco_PF(jTextFieldEditarEndereco.getText());
                clientepf.setBairro_PF(jTextFieldEditarBairro.getText());
                clientepf.setEstado_PF(jTextFieldEditarEstado.getText());
                clientepf.setTelefone_PF(jTextFieldEditarTelefone.getText());
                clientepf.setCidade_PF(jTextFieldEditarCidade.getText());

                NegocioClientePF negocioClientePF = new NegocioClientePF();
                negocioClientePF.editarClientePF(clientepf);
                JOptionPane.showMessageDialog(this, "Cliente editado", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                ListarCpfTable();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Atenção", JOptionPane.WARNING_MESSAGE);

            }
        }
        if (jRadioButtonListarJuridicas.isSelected()) {
            try {
                
                ClientePJ clientepj = new ClientePJ();
                clientepj.setRazaoSocial(jTextFieldEditarNome.getText());
                clientepj.setNomeEmpresa(jTextFieldEditarEmpresa.getText());
                clientepj.setCnpj(jTextFieldEditarCPF.getText());
                clientepj.setEndereco_PJ(jTextFieldEditarEndereco.getText());
                clientepj.setBairro_PJ(jTextFieldEditarBairro.getText());
                clientepj.setEstado_PJ(jTextFieldEditarEstado.getText());
                clientepj.setTelefone_PJ(jTextFieldEditarTelefone.getText());
                clientepj.setCidade_PJ(jTextFieldEditarCidade.getText());

                NegocioClientePJ negocioClientePJ = new NegocioClientePJ();
                negocioClientePJ.editarClientePJ(clientepj);
                JOptionPane.showMessageDialog(this, "Cliente editado", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                ListarCnpjTable();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Atenção", JOptionPane.WARNING_MESSAGE);
            }
        }
       
    }//GEN-LAST:event_jButtonConcluirEdicaoActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        try {
            if (jRadioButtonListarFisicas.isSelected() == true) {
                ClientePF clientepf = new ClientePF();
                DadosClientePF dadosClientePF = new DadosClientePF();
                clientepf.setCpf(jTextFieldPesquisarCPF.getText());
                this.respostaClientePF = dadosClientePF.listarClientePF(clientepf);
                DefaultTableModel modelo = new DefaultTableModel();
                modelo.setColumnIdentifiers(new Object[]{"Nome", "CPF", "Telefone"});

                for (ClientePF c : this.respostaClientePF) {
                    modelo.addRow(new Object[]{c.getNome(), c.getCpf(), c.getTelefone_PF()});
                }
                jTable1.setModel(modelo);
            }
            if (jRadioButtonListarJuridicas.isSelected() == true) {
                ClientePJ clientepj = new ClientePJ();
                DadosClientePJ dadosClientePJ = new DadosClientePJ();
                clientepj.setCnpj(jTextFieldPesquisarCPF.getText());
                this.respostaClientePJ = dadosClientePJ.listarClientePJ(clientepj);
                DefaultTableModel modelo = new DefaultTableModel();
                modelo.setColumnIdentifiers(new Object[]{"Razão Social", "CNPJ", "Empresa"});

                for (ClientePJ c : this.respostaClientePJ) {
                    modelo.addRow(new Object[]{c.getRazaoSocial(), c.getCnpj(), c.getNomeEmpresa()});
                }

                jTable1.setModel(modelo);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Atenção", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jTextFieldNomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNomeKeyTyped
        String caracteres = "0123456789/*-+./[]{}-_<>()&¬¢%$£#³@²¹!''|¨";      
        if(caracteres.contains(evt.getKeyChar() + ""))
        {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldNomeKeyTyped

    private void jTextFieldCPFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCPFKeyTyped
        String caracteres = "0123456789";       
        if(!caracteres.contains(evt.getKeyChar() + ""))
        {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldCPFKeyTyped

    private void jTextFieldTelefoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTelefoneKeyTyped
        String caracteres = "0123456789()-";       
        if(!caracteres.contains(evt.getKeyChar() + ""))
        {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldTelefoneKeyTyped

    private void jTextFieldPesquisarCPFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPesquisarCPFKeyTyped
        String caracteres = "0123456789";       
        if(!caracteres.contains(evt.getKeyChar() + ""))
        {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldPesquisarCPFKeyTyped

    private void jTextFieldCidadeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCidadeKeyTyped
        String caracteres = "0123456789/*-+./[]{}-_<>()&¬¢%$£#³@²¹!''|¨";      
        if(caracteres.contains(evt.getKeyChar() + ""))
        {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldCidadeKeyTyped

    private void jTextFieldEditarCPFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldEditarCPFKeyTyped
        String caracteres = "0123456789";       
        if(!caracteres.contains(evt.getKeyChar() + ""))
        {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldEditarCPFKeyTyped

    private void jTextFieldEditarEstadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldEditarEstadoKeyTyped
        String caracteres = "0123456789/*-+./[]{}-_<>()&¬¢%$£#³@²¹!''|¨";      
        if(caracteres.contains(evt.getKeyChar() + ""))
        {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldEditarEstadoKeyTyped

    private void jTextFieldEditarCidadeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldEditarCidadeKeyTyped
        String caracteres = "0123456789/*-+./[]{}-_<>()&¬¢%$£#³@²¹!''|¨";      
        if(caracteres.contains(evt.getKeyChar() + ""))
        {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldEditarCidadeKeyTyped

    private void jTextFieldDataKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDataKeyTyped
        String caracteres = "0123456789//";
        if(!caracteres.contains(evt.getKeyChar() + ""))
        {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldDataKeyTyped

    private void jTextFieldEditarBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEditarBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEditarBairroActionPerformed

    private void jTextFieldEditarTelefoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldEditarTelefoneKeyTyped
        String caracteres = "0123456789()-";       
        if(!caracteres.contains(evt.getKeyChar() + ""))
        {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldEditarTelefoneKeyTyped

    private void jTextFieldEstadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldEstadoKeyTyped
        String caracteres = "0123456789/*-+./[]{}-_<>()&¬¢%$£#³@²¹!''|¨";
        if(caracteres.contains(evt.getKeyChar() + ""))
        {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldEstadoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewCadastroClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewCadastroClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewCadastroClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewCadastroClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewCadastroClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButtonCadastrar;
    private javax.swing.JButton jButtonConcluirEdicao;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JLabel jLabelAviso;
    private javax.swing.JLabel jLabelAviso2;
    private javax.swing.JLabel jLabelBairro;
    private javax.swing.JLabel jLabelCPF;
    private javax.swing.JLabel jLabelCidade;
    private javax.swing.JLabel jLabelData;
    private javax.swing.JLabel jLabelEditarBairro;
    private javax.swing.JLabel jLabelEditarCPF;
    private javax.swing.JLabel jLabelEditarCidade;
    private javax.swing.JLabel jLabelEditarEmpresa;
    private javax.swing.JLabel jLabelEditarNome;
    private javax.swing.JLabel jLabelEditarTelefone;
    private javax.swing.JLabel jLabelEdtiarEndereco;
    private javax.swing.JLabel jLabelEdtiarEstado;
    private javax.swing.JLabel jLabelEndereco;
    private javax.swing.JLabel jLabelEstado;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelNomeEmpresa;
    private javax.swing.JLabel jLabelTelefone;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JRadioButton jRadioButtonClientePF;
    private javax.swing.JRadioButton jRadioButtonClientePJ;
    private javax.swing.JRadioButton jRadioButtonListarFisicas;
    private javax.swing.JRadioButton jRadioButtonListarJuridicas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldBairro;
    private javax.swing.JTextField jTextFieldCPF;
    private javax.swing.JTextField jTextFieldCidade;
    private javax.swing.JTextField jTextFieldData;
    private javax.swing.JTextField jTextFieldEditarBairro;
    private javax.swing.JTextField jTextFieldEditarCPF;
    private javax.swing.JTextField jTextFieldEditarCidade;
    private javax.swing.JTextField jTextFieldEditarEmpresa;
    private javax.swing.JTextField jTextFieldEditarEndereco;
    private javax.swing.JTextField jTextFieldEditarEstado;
    private javax.swing.JTextField jTextFieldEditarNome;
    private javax.swing.JTextField jTextFieldEditarTelefone;
    private javax.swing.JTextField jTextFieldEndereco;
    private javax.swing.JTextField jTextFieldEstado;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldNomeEmpresa;
    private javax.swing.JTextField jTextFieldPesquisarCPF;
    private javax.swing.JTextField jTextFieldTelefone;
    // End of variables declaration//GEN-END:variables
}
